#!/bin/bash

# read_ifs

FILE=/etc/passwd

read -p "Enter user name > " user_name

file_info="$(grep "^$user_name:" $FILE)"

if [ -n "$file_info" ]; then
	IFS=":" read user pw uid gid name home shell <<< "$file_info"
	echo "User =		'$user'"
	echo "UID =			'$uid'"
	echo "GID =			'$gid'"
	echo "Full Name =	'$name'"
	echo "Shell =		'$shell'"
	echo "Home dir. =	'$home'"
else
	echo "No such user '$user_name'" >$2
	exit 1
fi

